version: '3.8'

services:

  web:
    image: python:3.9
    container_name: django_web
    command: python manage.py runserver
    volumes:
      - ./registro:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:12
    
    environment:
      - POSTGRES_DB=registration_db
      - POSTGRES_USER=registration_user
      - POSTGRES_PASSWORD=registration_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  db_data:

networks:
  backend:
